### ISSUE TITLE
Error: maxObjectCount exceeded

### ISSUE THREAD

**Issue by psalkowski** [ladinu/bplist#1]
When I'm trying to parse large binary data (5mb and more) then I got error:

```
Error: maxObjectCount exceeded
    at exports.parseBuffer (E:\xampp\htdocs\projekty\test-project\node_modules\bplist-parser\bplistParser.js:78:11)
    at tryParseBuffer (E:\xampp\htdocs\projekty\test-project\node_modules\bplist-parser\bplistParser.js:27:16)
    at Object.exports.parseFile (E:\xampp\htdocs\projekty\test-project\node_modules\bplist-parser\bplistParser.js:35:12)
    at Statement.<anonymous> (E:\xampp\htdocs\projekty\test-project\index.js:9:22)
    at Statement.replacement (E:\xampp\htdocs\projekty\test-project\node_modules\sqlite3\lib\trace.js:20:31)
    at Statement.replacement (E:\xampp\htdocs\projekty\test-project\node_modules\sqlite3\lib\trace.js:20:31)
```

My code:

```
bplistParser.parseFile(row.value, function(err, dicts) {
    console.log(err);
});
```

**Comment by ladinu** [comment]
Try setting `bplistParser.maxObjectSize` to something higher than 5mb
